# **Chapter 1 머신러닝과 딥러닝**

# **Chapter 2 실습 환경 설정과 파이토치 기초**

### **[개념 정리]**

#### **1.1 인공지능, 머신러닝과 딥러닝**

인공지능(Artificial Intelligence, AI)
> 인간의 지능을 모방하여 사람이 하는 일을 기계가 할 수 있도록 하는 기술
> 인공지능과 머신러닝, 딥러닝의 관계

머신러닝
> 주어진 데이터를 인간이 먼저 전처리 해주어야 함.
> 만약 이미지 데이터라면 사람이 학습 데이터를 컴퓨터가 인식할 수 있도록 준비해 두어야 하는 것
> - 따라서, 머신러닝은 범용적 목적을 위해 제작된 것으로 데이터의 특징을 스스로 추출하지 못함.
- 머신러닝의 학습 과정
  > 각 데이터 특성을 기계에 인식시키고 학습시켜 문제를 해결

딥러닝
> 인간이 하던 작업(머신러닝에서 언급한 부분)을 생략
> 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석한 후 답을 찾음

머신러닝과 딥러닝의 차이

#### **1.2 머신러닝이란**

머신러닝
> 인공지능의 한 분야로, 컴퓨터 스스로 대용량 데이터에서 지식이나 패턴을 찾아 학습하고 예측을 수행하는 것

##### **1.2.1 머신러닝 학습 과정**

머신러닝의 주요 구성 요소

1. 데이터
> 머신러닝이 학습 모델을 만드는 데 사용한느 것
> 실제 데이터의 특징이 잘 반영되고, 편향되지 않는 훈련 데이터를 확보하는 것이 중요
> - 학습에 필요한 데이터가 수집되었다면, '훈련 데이터셋'과 '테스트 데이터셋'으로 분리하여 사용

2. 모델(모형)
> 머신러닝의 학습 단계에서 얻은 최종 결과물
> - 모델의 학습 절차
>   1. 모델 선택
>   2. 모델 학습 및 평가
>   3. 평가를 바탕으로 모델 업데이트
> - 훈련과 검증, 테스트 데이터셋
> - 모델 성능 평가가 필요한 이유
>   1. 테스트 데이터셋에 대한 성능을 가늠해볼 수 있음
>   2. 모델 성능을 높이는 데에 도움
>      - 만약, 훈련 데이터셋에 대한 정확도는 높은데, 검증 데이터셋에 대한 정확도가 낮다면 훈련 데이터셋에 과적합이 일어났을 가능성 존재 -> 정규화를 하거나 에포크를 줄이는 방식으로 과적합 방지 가능

##### **1.2.2 머신러닝 학습 알고리즘**

1. 지도 학습
> 정답이 무엇인지 컴퓨터에 알려주고 학습시키는 방법

2. 비지도 학습
> 정답을 알려주지 않고, 특징이 비슷한 데이터를 클러스터링하여 예측하는 학습 방법

3. 강화 학습
> 자신의 행동에 대한 보상을 받으며 학습을 진행

#### **1.3 딥러닝이란**

딥러닝
> 인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신러닝 방법의 일종
> 머신러닝과의 차이점은 인간의 뇌를 기초로 하여 설계했다는 점

##### **1.3.1 딥러닝 학습 과정**

1. 데이터 준비

2. 모델 정의
> 일반적으로 은닉층 개수가 많을수록 성능이 좋아히지만, 과적합 발생 확률이 높음

3. 모델 컴파일
> 활성화 함수, 손실 함수, 옵티마이저 선택 (과적합을 피하는 것이 중요)

4. 모델 훈련
> 에포크 선택의 중요성
> - 한 번에 처리해야 할 데이터양이 많아지면 학습 속도가 느려지고 메모리가 부족해지는 문제를 야기하기 때문에, 적당한 데이터 묶음을 선택하는 것이 중요
> 배치 크기 선택
> - '훈련 데이터셋 1000개에 대한 배치 크기가 20'이라면 샘플 단위 20개마다 모델 가중치를 한 번씩 업데이트
> - 즉, 총 50번의 가중치가 업데이트
> - 여기서 에포크가 10이면 가중치를 50번 업데이트하는 것을 총 10번 반복한다는 의미
> - 결과적으로, 가중치가 총 500번 업데이트

5. 모델 예측
> 성능이 좋다는 의미?
> - 궁극적으로 모델 성능은 데이터가 수집된 산업 분야와 모델이 생성된 목적에 의존한다고 볼 수있음

딥러닝에서 중요한 핵심 구성 요소

1. 신경망
> 심층 신경망
> - 데이터셋의 어떤 특성들이 중요한 지 스스로에게 가르쳐 줄 수 있는 기능 탑재

2. 역전파
> 가중치 값을 업데이트하기 위함

##### **1.3.2 딥러닝 학습 알고리즘**

1. 지도 학습
> 이미지 분류
> - 이미지 또는 비디오상의 객체를 식별하는 컴퓨터 비전 기술
> - 컴퓨터 비전에서 가장 많이 사용되는 것이 합성곱 신경망(CNN)

- 합성곱 신경망
  1. 이미지 분류
  > 이미지를 알고리즘에 입력하면 그 이미지가 어떤 클래스에 속하는지 알려줌 -> 이미지 데이터를 유사한 것끼리 분류할 때 사용
  
  2. 이미지 인식
  > 사진을 분석하여 그 안에 있는 사물의 종류를 인식하는 것

  3. 이미지 분할
  > 영상에서 사물이나 배경 등 객체 간 영역을 픽셀 단위로 구분하는 기술

> 시계열 데이터를 분류할 때 사용되는 것이 순환 신경망(RNN)
> - 역전파 과정에서 기울기가 소멸하는 문제가 발생하는 단점으로, 게이트(Gate)를 3개 추가한 LSTM 사용

2. 비지도 학습
> 1. 워드 임베팅
> - 자연어를 컴퓨터가 이해하고 효율적으로 처리하게 하려면 컴퓨터가 이해할 수 있도록 자연어를 적절히 변환하는 과정 (단어)
> - 단어 의미를 벡터화하는 워드투벡터(Word2Vec), 글로브(Glove) 사용
> 2. 군집
> - 아무런 정보가 없는 상태에서 데이터를 분류하는 방법
> - 머신러닝의 군집과 다르지 않음. 하지만, 머신러닝에서 군집화를 처리할 때 딥러닝과 함께 사용하면 모델 성능을 높일 수 있어 머신러닝 단독으로 군집 알고리즘을 적용하기보단 딥러닝과 함께 사용하는 것이 좋음.

3. 전이 학습
> 사전에 학습이 완료된 모델(사전 학습 모델)을 가지고 우리가 원하는 학습에 미세 조정 기법을 이용하여 학습시키는 방법
> 사전 학습 모델
> - 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모델

#### **2.1 파이토치 개요**

파이토치(PyTorch)
> 1. 넘파이를 대체하면서 GPU를 이용한 연산이 필요한 경우
> 2. 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

##### **2.1.1 파이토치 특징 및 장점**

GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크

- GPU: 연산 속도를 빠르게 하는 역할
- 텐서(Tensor): 파이토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬
- 동적 신경망: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망

인공지능에서 데이터는 벡터로 표현됨

##### **2.1.2 파이토치의 아키텍처**

파이토치 API
- torch: GPU를 지원하는 텐서 패키지
- torch.autograd: 자동 미분 패키지
- torch.nn: 신경망 구축 및 훈련 패키지
- torch.multiprocessing: 파이씬 멀티프로세싱 패키지
- torch.utils: DataLoader 및 기타 유틸리티를 제공하는 패키지

파이토치 엔진

연산 처리
- 가장 아래 계층에 속하는 C 또는 CUDA 패키지는 상위의 API에서 할당된 거의 모든 계산을 수행

#### **2.2 파이토치 기초 문법**

#### **2.2.3 모델 정의**

- 계층(layer)
> 모듈 또는 모듈을 구성하는 1개의 계층으로 합성곱층(convolutional layer), 선형계층(linear layer) 등

- 모듈(module)
> 1개 이상의 계층이 모여서 구성된 것

- 모델(model)
> 최종적으로 원하는 네트워크

### **[필사]**

#### **2.1 파이토치 개요**

##### **2.1.1 파이토치 특징 및 장점**

In [ ]:
import torch
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

##### **2.2.1 텐서 다루기**

텐서 생성 및 변환

In [1]:
import torch
print(torch.tensor([[1, 2], [3, 4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1, 2], [3, 4]], device="cuda:0")) # GPU에 텐서 생성
print(torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [2]:
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.numpy()) # 텐서를 ndarray로 변환

[[1 2]
 [3 4]]


In [3]:
temp = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
print(temp.to("cpu").numpy()) # GPU상의 텐서를 CPU의 텐서로 변환할 후 ndarray로 변환

[[1 2]
 [3 4]]


텐서의 인덱스 조작

- torch.FloatTensor: 32비트의 부동 소수점
- torch.DoubleTensor: 64비트의 부동 소수점
- torch.LongTensor: 64비트의 부호가 있는 정수

In [4]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7]) # 파이토치로 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print('--------------------------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
--------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


텐서 연산 및 차원 조작

In [5]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v) # 길이가 같은 벡터 간 뺄셈 연

tensor([2, 2, 3])


In [6]:
temp = torch.tensor([
    [1, 2], [3, 4]
])

print(temp.shape)
print('-----------------------------')
print(temp.view(4, 1))
print('-----------------------------')
print(temp.view(-1))
print('-----------------------------')
print(temp.view(1, -1))
print('-----------------------------')
print(temp.view(-1, 1))

torch.Size([2, 2])
-----------------------------
tensor([[1],
        [2],
        [3],
        [4]])
-----------------------------
tensor([1, 2, 3, 4])
-----------------------------
tensor([[1, 2, 3, 4]])
-----------------------------
tensor([[1],
        [2],
        [3],
        [4]])


#### **2.2.2 데이터 준비**

단순하게 파일을 불러와서 사용

In [8]:
# import pandas as pd
# import torch
# data = pd.read_csv('../class2.csv')

# x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
# y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

커스텀 데이터셋을 만들어서 사용

In [9]:
# import pandas as pd
# import torch
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader

# class CustomDataset(Dataset):
#   def __init__(self, csv_file):
#     self.label = pd.read_csv(csv_file)

#   def __len__(self):
#     return len(self.label)

#   def __getitem__(self, idx):
#     sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
#     label = torch.tensor(self.label.iloc[idx, 3]).int()
#     return sample, label

# tensor_dataset = CustomDataset('../covtype.csv')
# dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)

In [10]:
# for i data in enumerate(dataset, 0):
#   print(i, end='')
#   batch=data[0]
#   print(batch.size())

파이토치에서 제공하는 데이터셋 사용

In [11]:
!pip install requests

In [12]:
# import torchvision.transform as transforms

# mnist_transform = transforms.Compose([
#     transforms.ToTensor(),
#     transforms.Normalize((0.5,), (1.0,))
# ])

# from torchivision.datasets import MNIST
# import requests

# train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
# valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
# test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

#### **2.2.3 모델 정의**

단순 신경망을 정의하는 방법

In [14]:
# model = nn.Linear(in_features=1, out_features=1, bias=True)

nn.Module()을 상속하여 정의 하는 방법

In [17]:
# class MLP(Module):
#   def __init__(self, inputs):
#     super(MLP, self).__init__()
#     self.layer = Linear(inputs, 1)
#     self.activation = Sigmoid()

#   def forward(self, X):
#     X = self.layer(X)
#     X = self.activation(X)
#     return X

Sequential 신경망을 정의하는 방법

In [20]:
import torch.nn as nn
class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2)

    )

    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2)

    )

    self.layer3 = nn.Sequential(
        nn.Linear(in_features=30*5*5, out_features=10, bias=True),
        nn.ReLU(inplace=True)
    )

    def forward(self, x):
      x = self.layer1(x)
      x = self.layer2(x)
      x = x.view(x.shape[0], -1)
      x = self.layer3(x)
      return x

model = MLP()

print ("Printing children\n------------------------------")
print(list(model .children()))
print ("\n\nPrinting Modules\n------------------------------")
print(list(model .modules()))

Printing children
------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linea

nn.Sequential은 모델의 계층이 복잡할수록 효과가 뛰어남

함수로 신경망을 정의하는 방법

In [21]:
def MLP(in_features=1, hidden_features=20, out_features=1):
  hidden = nn.Linear(in_features=in_features, out_features=hidden_features, bias=True)
  activation = nn.ReLU()
  output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
  net = nn.Sequential(hidden, activation, output)
  return net

##### **2.2.4 모델의 파라미터 정의**

In [24]:
# from torch.optim import optimizer
# criterion = torch.nn.MSELoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
# scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda=lambda epoch: 0.95 ** epoch)

# for epoch in range(1, 100+1):
#   for x, y in dataloader:
#     optimizer.zero_grad()
# loss_fn(model(x), y).backward()
# optimizer.step()
# scheduler.step()

##### **2.2.5 모델 훈련**

In [26]:
# for epoch in range(100):
#   yhat = model(x_train)
#   loss = criterion(x_train)
#   optimizer.zero_grad()
#   loss.backward()
#   optimizer.step()

##### **2.2.6 모델 평가**

In [27]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 56.3 MB/s eta 0:00:00


In [30]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10, ))

acc = torchmetrics.functional.accuracy(preds, target, task="multiclass", num_classes=5)