<a href="https://colab.research.google.com/github/jiiwon129/ESAA/blob/main/YB0307_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
import numpy as np

array1=np.random.random((5,3))
array2=np.random.random((3,2))

print('5x3 Matrix:',array1)
print('\n')
print('3x2 Matrix:',array2)
print('\n')
print('Result:\n', np.dot(array1,array2))

5x3 Matrix: [[0.22737337 0.3211778  0.76666863]
 [0.08244223 0.96050326 0.07646404]
 [0.29369274 0.82610022 0.67121925]
 [0.4487142  0.3344116  0.95471842]
 [0.59126934 0.95339911 0.35753695]]


3x2 Matrix: [[0.37360771 0.27946372]
 [0.59490438 0.50534525]
 [0.03160655 0.06073895]]


Result:
 [[0.30025027 0.27241493]
 [0.60462541 0.51306971]
 [0.62239144 0.54031144]
 [0.39676137 0.35238125]
 [0.7993846  0.66875046]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
array1D=np.arange(10)
array1D[(array1D > 3) & (array1D < 8)]*=-1
print(array1D)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9

10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

**< legal >**

Z**Z

2<< Z >> 2

1j*Z

Z/1/1

**< illegal >**

Z <- Z

Z < Z > Z

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-31-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-31-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-31-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [30]:
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print('Z1:',Z1)
print('Z2:',Z2)
print(np.intersect1d(Z1,Z2))

Z1: [2 2 0 4 4 2 6 4 0 9]
Z2: [1 7 4 7 8 1 8 8 4 2]
[2 4]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-32-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [23]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [39]:
A=np.random.randint(10)
B=np.random.randint(10)
C=np.add(A,B)
D=np.negative(A)
E=np.divide(D,2)
F=np.multiply(A,E)
print(F)

-32.0


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [42]:
array=np.random.randint(10,size=10)
print(array//1)
print(array%1)

[5 3 4 3 9 2 9 0 9 6]
[0 0 0 0 0 0 0 0 0 0]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [44]:
array=np.random.randint(5,size=(5,5))
print(array)

[[3 3 3 2 4]
 [3 3 4 0 2]
 [3 4 3 0 0]
 [4 4 1 2 3]
 [4 2 4 1 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [36]:
array=np.random.random(10)
print(np.sort(array))

[0.00484905 0.14824867 0.32995495 0.34326991 0.41243939 0.42245905
 0.54971103 0.61136214 0.81502337 0.83876793]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [45]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [46]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.072927   0.3816885  0.96723738 0.92527092 0.32781888 0.42990232
 0.81022828 0.87888287 0.74039059 0.24847684]
[0.42774061 1.56931367 0.06352874 1.06301422 1.5507006  0.18437616
 1.1229794  0.16530272 1.0538941  1.49798237]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [47]:
Z=np.random.randint(0,10,10)
Z[Z.argmax()]=0
print(Z)

[6 0 4 6 0 5 1 5 6 3]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [48]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distance=np.abs(Z-v)

closest_index=np.argmin(distance)
Z[closest_index]

9

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [49]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [64]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
print(Z)

[[0. 0. 0.]
 [0. 8. 0.]
 [0. 0. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [59]:
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[0 2 0]
 [9 6 2]
 [2 6 5]]
[[0 2 0]
 [2 6 5]
 [9 6 2]]


In [60]:
print(Z)
print(Z[Z[:,1].argsort()])

[[0 2 0]
 [9 6 2]
 [2 6 5]]
[[0 2 0]
 [9 6 2]
 [2 6 5]]


In [62]:
print(Z)
print(Z[Z[:,2].argsort()])

[[0 2 0]
 [9 6 2]
 [2 6 5]]
[[0 2 0]
 [9 6 2]
 [2 6 5]]
