<a href="https://colab.research.google.com/github/jiiwon129/ESAA/blob/main/ESAA_YB_WEEK4_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **[ 개념정리 ]**

**01 사이킷런 소개와 특징**

---

사이킷런(scikit-learn)
- 파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러라

**02 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기**

---

지도학습(Supervised Learning)
- 다양한 feature와 label 데이터로 모델을 학습한 후, 테스트 데이터 세트에서 label을 예측
- 명확한 정답이 주어진 데이터를 먼저 학습 후, 미지의 정답을 예측하는 방식

train dataset: 학습을 위한 데이터
test dataset: 머신러닝 모델의 예측 성능을 평가하기 위한 데이터

필요한 모듈 패키지 임포트


```
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
```

- 붓꽃 데이터 세트 로딩
```
load_iris()
```
  - iris.data: iris 데이터 세트에서 feature만으로 된 데이터를 numpy로 가짐
  - iris.target: iris 데이터에서 label 데이터를 numpy로 가짐

학습용 데이터와 테스트용 데이터 분리
```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size, random_state)
```
- data(X): feature 데이터셋
- label(y): label 데이터셋
- test_size: 전체 데이터셋 중 **테스트** 데이터셋의 비율
- random_state: 호출할 때마다 같은 학습/테스트 용 데이터셋을 생성하기 위해 주어지는 난수 발생 값
 - train_test_split()은 호출 시 무작위로 데이터를 분리하기 때문에 random_state를 지정해야함

train_test_split()
- X_train을 X_test로 반환
- y_train을 y_test로 반환

DecisionTreeClassifier 객체 생성
```
dt_clf=DecisionTreeClassifier(random_state)
dt_clf.fit(X_train,y_train)
dt_clf.predict(X_test)
```

예측 성능
```
from sklearn.metrics import accuracy_score
accuracy_score(y_test,dt_clf.predict(X_test))
```

<Classification로 예측한 process>
1. 데이터 셋 분리
2. 모델 학습
3. 예측 수행
4. 평가

**03 사이킷런의 기반 프레임워크 익히기**

---

**Estimator 이해 및 fit(), predict() 메서드**

Estimator
- 지도학습의 모든 알고리즘을 구현한 클래스를 통칭
- Classifier와 Regressor를 합쳐서 Estimator 클래스라 부름
- 내부에서 fit(), predict() 구현
- cross_val_score()와 같은 evaluation 함수, GridSearchCV와 같은 하이퍼 파라미터 튜닝을 지원하는 클래스에서 Estimator 인자를 받음

**내장된 데이터세트 예제**

사이킷런 내장 데이터셋은 일반적으로 딕셔너리 형태
- < key>
 - data(ndarray): feature의 데이터셋
 - target(ndarray): classification -> label 값, regression -> 숫자 결과값 데이터셋
 - target_names(ndarray or list): 개별 label의 이름
 - feature_names(ndarray or list): feature의 이름
 - DESCR(string): 데이터셋에 대한 설명과 각 feature의 설명





**04 Model Selection 모듈 소개**

---

**학습/테스트 데이터 세트 분리 - train_test_split()**

- test_size: 전체 데이터에서 테스트 데이터셋 크기의 비율 (default=0.25)
- train_size: 전체 데이터에서 학습용 데이터셋 크기의 비율 (test_size를 통상적으로 사용하기 때문에 잘 사용X)
- shuffle: 데이터 분리 전 미리 섞을 지 결정(default=True)
- random_state: 호출할 때마다 동일한 학습/테스트용 데이터셋을 생성하기 위해 주어지는 난수 발생 값
 - 수행할 때마다 동일한 데이터 셋으로 분리하기 위해 random_state에 일정한 숫자 값 부여

**교차 검증**

- 과적합 같은 문제점을 개선

**K 폴드 교차 검증**
- K개의 데이터 폴드 세트를 만들어 K번만큼 각 폴드 세트에 학습과 검증 평가를 반복적 수행

< 순서 >
1. 폴드 세트 설정
2. for 루프에서 반복으로 학습 및 테스트 데이터의 인덱스 추출
3. 반복적으로 학습과 예측 수행 후 예측 성능 반환


```
from sklearn.model_selection import KFold
dt_clf=DecisionTreeClassifier(random_state)

# KFold 객체 생성
KFold(n_splits=k)
```
- KFold 객체 생성 후 생성된 KFold 객체의 split() 호출하여 데이터를 k개의 폴드 데이터 셋으로 분리

```
n_iter = 0

for train_index, test_index in kfold.split(features)：
  X_train, X_test = features[train_index]z features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1

  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]

  cv_accuracy.append(accuracy)
```

**Stratified K 폴드**

- 불균형한(imbalanced) 분포를 가진 label 데이터 집합을 위한 K 폴드 방식
- KFold로 분할된 label 데이터셋이 전체 label 값의 분포도를 반영하지 못하는 문제를 해결

```
from sklearn.model_selection import StratifiedKFold
dt_clf=DecisionTreeClassification

skf=StratifiedKFold(n_splits=k)
```

```
n_iter=0
cv_accuracy=[]

for train_index, test_index in skfold.split(features, label):
  X_train,X_test=features[train_index],features[test_index]
  y_train,y_test=label[train_index],label[test_index]

  dt_clf.fit(X_train,y_train)
  pred=dt_clf.predict(X_test)

  n_iter+=1
  accuracy=np.round(accuracy_score(y_test,pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]

  cv_accuracy.append(accuracy)
```

- Classification에서의 교차 검증은 일반적으로 Stratified K 폴드로 분할되어야함
- Regression에서는 Stratified K 폴드가 지원되지 X -> 회귀의 결정값은 연속된 숫자값이기 때문에 이산값 형태의 label이 아님

**교차 검증을 보다 간편하게 - cross_val_score()**

cross_val_score(**estimator**, **X**, **y=None**, **scoring=None**, **cv=None**, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs')
- estimator: Classifier or Regressor
- X: feature dataset
- y: label dataset
- scoring: 예측 성능 평가 지표
- cv: 교차 검증 폴드 수

- 수행 후 반환 값: scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환

Classifier: Stratified K 폴드 방식으로 분할

Regressor: Stratified K 폴드 방식으로 분할X, K 폴드 방식으로 분할

```
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selction import cross_val_score, cross_validate

dt_clf=DecisionTreeClassifier(random_state)
cross_val_score(dt_clf,data,label,scoring='accuracy',cv=k)
```

cross_val_score()
- 단 1개의 평가 지표만 가능
- 보통 이거로 대부분의 경우 쉽게 사용 가능

cross_validate()
- 여러 개의 평가 지표 반환 가능
- 학습 데이터에 대한 성능 평가 지표와 수행 시간 제공

**GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에**

하이퍼 파라미터
- 머신러닝 알고리즘을 구성하는 주요 구성 요소
- 이를 조정하여 알고리즘의 예측 성능 개선

GridSearchCV
- 교차 검증을 기반으로 하이퍼 파라미터의 최적 값을 찾게 해줌
- estimator: classifier, regressor, pipeline
- param_grid: key + list 값을 가지는 딕셔너리가 주어짐. estimator 튜닝을 위해 파라미터명과 사용될 여러 파라미터의 값을 지정
- scoring: 예측 성능을 측정할 평가 방법 지정
- cv: 교차 검증을 위해 분할되는 데이터의 개수 지정
- refit: 가장 최적의 하이퍼 파라미터를 찾은 뒤 입력된 estimator 객체를 해당 하이퍼 파라미터로 재학습 (default=True)

```
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

X_train,X_test,y_train,y_test=train_test_split(data,label,test_size,random_state)

dt_clf=DecisionTreeClassifier()

parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}
```

```
grid_dt_clf=GridSearch(dt_clf,param_grid=parameters,cv=k,refit=True)

grid_dt_clf.fit(X_train,y_train)
df=pd.DataFrame(grid_dt_clf.cv_results_)
```

< columns 의미 >
- params: 수행할 때마다 적용된 개별 하이퍼 파라미터값
- rank_test_score: 하이퍼 파라미터별로 성능이 좋은 score 순위 (1일 때가 최적)
- mean_test_score: 개별 하이퍼 파라미터별로 CV의 폴딩 테스트셋에 대해 총 수행한 평가 평균값

GridSearchCV 최적의 파라미터
- grid_dt_clf**.best_params**

GridSearchCV 최고 정확도
- grid_dt_clf**.best_score_**

GridSearchCV의 refit으로 이미 학습된 estimator 반환
- estimator=grid_dt_clf**.best_estimator_**
 - 이미 최적 학습이 되었으므로 별도의 학습이 필요X
 - estimator.predict(X_test)

### **[ 필사 ]**

##### **01 사이킷런 소개와 특징**

In [1]:
pip install scikit-learn==1.0.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 30.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
import sklearn

print(sklearn.__version__)

1.6.1


##### **02 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기**

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [ ]:
import pandas as pd

# 붓꽃 데이터 세트를 로딩합니다.
iris=load_iris()

# iris.data는 Iris 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data=iris.data

# iris.target은 붓꽃 데이터 세트에서 label 데이터를 numpy로 가지고 있습니다.

iris_label=iris.target
print('iris target값:',iris_label)
print('iris target명:',iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DateFrame으로 변환합니다.
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(iris_data,iris_label,
                                               test_size=0.2,random_state=11)

In [ ]:
# DecisionTreeClassifie 객체 생성
df_clf=DecisionTreeClassifier(random_state=11)

In [ ]:
# 학습 수행
df_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [ ]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 에측 수행.
pred=df_clf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


##### **03 사이킷런의 기반 프레임워크 익히기**

Estimator 이해 및 fit(), predict() 메서드

사이킷런의 주요 모듈

내장된 예제 데이터 세트

In [ ]:
from sklearn.datasets import load_iris

iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('\n feature_names의 type:',type(iris_data.feature_names))
print(' feature_names의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:',type(iris_data.target_names))
print(' target_names의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:',type(iris_data.data))
print(' data의 shape:',iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:',type(iris_data.target))
print(' target의 shape:',iris_data.target.shape)
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
 data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5

##### **04 Model Selection 모듈 소개**

학습/테스트 데이터 세트 분리 - train_test_split()

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data,train_label)

# 학습 데이터 세트로 예측 수행
pred=dt_clf.predict(train_data)
print('예측 정확도:',accuracy_score(train_label,pred))

예측 정확도: 1.0


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf=DecisionTreeClassifier()
iris_data=load_iris()

X_train,X_test,y_train,y_test=train_test_split(iris_data.data,iris_data.target,
                                               test_size=0.3,random_state=121)

In [ ]:
dt_clf.fit(X_train,y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556


교차 검증

K 폴드 교차 검증

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 kFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성.
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [ ]:
n_iter=0

# KFold 객체의 split()를 호출하면 폴드별 학습용, 검증용 테스트의 row 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train,X_test=features[train_index],features[test_index]
  y_train,y_test=label[train_index],label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train,y_train)
  pred=dt_clf.predict(X_test)
  n_iter+=1
  # 반복 시마다 정확도 측정
  accuracy=np.round(accuracy_score(y_test,pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'
        .format(n_iter,accuracy,train_size,test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:',np.mean(cv_accuracy))


#1 교차 검증 정확도:1.0, 학습 데이터 크기:120, 검증 데이터 크기:30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도:0.9667, 학습 데이터 크기:120, 검증 데이터 크기:30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도:0.8667, 학습 데이터 크기:120, 검증 데이터 크기:30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도:0.9333, 학습 데이터 크기:120, 검증 데이터 크기:30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도:0.7333, 학습 데이터 크기:120, 검증 데이터 크기:30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


Stratified K 폴드

In [ ]:
import pandas as pd

iris=load_iris()
iris_df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [ ]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n',label_train.value_counts())
  print('검증 레이블 데이터 분포:\n',label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    50
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
Name: count, dtype: int64


In [ ]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df,iris_df['label']):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n',label_train.value_counts())
  print('검증 레이블 데이터 분포:\n',label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64


In [ ]:
dt_clf=DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split() 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features,label):
  # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train,X_test=features[train_index],features[test_index]
  y_train,y_test=label[train_index], label[test_index]
  # 학습 및 예측
  dt_clf.fit(X_train,y_train)
  pred=dt_clf.predict(X_test)

  # 반복 시마다 정확도 측정
  n_iter+=1
  accuracy=np.round(accuracy_score(y_test,pred),4)
  train_size=X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'
        .format(n_iter,accuracy,train_size,test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:',np.round(cv_accuracy,4))
print('## 평균 검증 정확도:',np.round(np.mean(cv_accuracy),4))


#1 교차 검증 정확도:0.98, 학습 데이터 크기:100, 검증 데이터 크기:50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도:0.94, 학습 데이터 크기:100, 검증 데이터 크기:50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도:0.98, 학습 데이터 크기:100, 검증 데이터 크기:50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9667


교차 검증을 보다 간편하게 - cross_val_score()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

# 성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


**GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에**

In [ ]:
grid_parameters={'max_depth':[1,2,3],
                 'min_samples_split':[2,3]}

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris_data.data,iris_data.target,
                                               test_size=0.2,random_state=121)
dtree=DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

In [ ]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정.
### refit=True가 default임. True이면 가장 좋은 파라미터 설정으로 재학습시킴.
grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)

# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train,y_train)

# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score',
           'split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [ ]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [ ]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator=grid_dtree.best_estimator_
# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도: 0.9667
