<a href="https://colab.research.google.com/github/jiiwon129/ESAA/blob/main/ESAA_YB_WEEK1_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [87]:
array1=np.array([1,2,3,4,5])
print(array1.nbytes)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array1=np.zeros(10)
array1[4]=1
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(np.arange(10,50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1=np.arange(0,9)
print(array1.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array1=np.array([1,2,0,0,4,0])
indices=np.where(array1!=0)
print(indices[0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
help(np.identity)
help(np.eye)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    

In [ ]:
print(np.identity(3))
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
print(np.random.random((3,3,3)))

[[[0.4746142  0.25379004 0.50838085]
  [0.98643148 0.40341876 0.68369126]
  [0.86373446 0.64989675 0.97871151]]

 [[0.57094058 0.78674925 0.97532503]
  [0.03289455 0.19338823 0.4025647 ]
  [0.11103373 0.07914286 0.16385361]]

 [[0.84467035 0.24319981 0.96798026]
  [0.2707667  0.3575323  0.29888272]
  [0.97313383 0.59694189 0.12163523]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_array=np.random.random((10,10))
print(random_array)
print('Minimum:', np.min(random_array))
print('Maximum:', np.max(random_array))

[[0.02823213 0.04511153 0.34046546 0.52645962 0.71276504 0.60998109
  0.26137281 0.21916573 0.87934794 0.83183137]
 [0.21280188 0.53421834 0.26180917 0.0237866  0.62536413 0.59155389
  0.52776007 0.31668832 0.71384274 0.33687507]
 [0.42419121 0.75515684 0.25792766 0.15413937 0.38602876 0.02241675
  0.23460458 0.97531129 0.82388543 0.8271415 ]
 [0.80254573 0.53862693 0.07669549 0.58012879 0.21225517 0.22327592
  0.10147009 0.61374439 0.1710362  0.60827832]
 [0.40588057 0.79041005 0.43545389 0.30096124 0.69311572 0.8129969
  0.30753215 0.15721592 0.4158836  0.63156387]
 [0.09096342 0.21825189 0.53451087 0.9186141  0.50428047 0.58566256
  0.54048661 0.3183811  0.21940892 0.33938095]
 [0.37223858 0.73267502 0.92099535 0.89612301 0.34803811 0.72964595
  0.22098369 0.91864336 0.11305784 0.15621939]
 [0.76522095 0.81630434 0.69133548 0.73801583 0.82583959 0.2550028
  0.01815644 0.76519815 0.17019897 0.10461342]
 [0.40616123 0.18378237 0.67604173 0.5492638  0.25353512 0.47154104
  0.62812054 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_array=np.random.random(30)
print(random_array)
print('Mean:', np.mean(random_array))

[0.64515179 0.90261516 0.23928072 0.2146153  0.87073481 0.79283743
 0.15993178 0.66781038 0.64111219 0.89299451 0.09507702 0.49749819
 0.87453466 0.43429718 0.9060483  0.39687056 0.89416844 0.33738753
 0.39454122 0.63897162 0.01106549 0.22254903 0.91357699 0.30311277
 0.73455873 0.16698777 0.17411196 0.12173781 0.37963641 0.80609659]
Mean: 0.5109970776942713


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array2d=np.ones((5,5))
array2d[1:-1,1:-1]=0
print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array1=np.diag([1,2,3,4],k=-1)
print(array1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array1=np.zeros((8,8))
array1[1::2,::2]=1
array1[::2,1::2]=1
print(array1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [86]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
random_array=np.random.random((5,5))
mean=np.mean(random_array)
std=np.std(random_array)
normalized_array=(random_array-mean)/std
print(normalized_array)

[[ 1.24440482  0.57822535  1.21099645 -1.10772554 -0.04350616]
 [-1.95305234 -1.89916586 -0.74453777  0.47736556 -0.59811097]
 [ 0.55322355 -0.2719944   0.99749887  1.44988934 -1.18757343]
 [ 0.11223671 -1.60797873  0.20996716 -0.67746995 -0.28318871]
 [ 0.54289271  1.46274745  0.90234897  0.73027973 -0.09777278]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
print(np.dtype([('Red',np.ubyte),('Green',np.ubyte),('Blue',np.ubyte),('Alpha',np.ubyte)]))

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
array1=np.random.random((5,3))
array2=np.random.random((3,2))
print(np.dot(array1,array2))

[[0.62539032 1.59503406]
 [0.90629314 1.46974192]
 [0.42754686 1.18068844]
 [0.58340451 0.83808061]
 [0.62322751 1.61934744]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array1=np.arange(10)
array1[(array1>3)&(array1<8)]*=-1
print(array1)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
